---
###Mod Assist
# 1 #Automatically remove anything that gets 3+ reports and send modmail
    reports: 3
    action: remove
    comment: "Your {{kind}} has been removed because multiple users has reported it to the moderation team. This action is done automatically by a bot. The moderators will review this action."
    modmail: "The above {{kind}} by /u/{{author}} was automatically removed due to receiving 3+ reports. [Please investigate]({{permalink}})."
 
---
# 2 #Automatically notifies via modmail of 2 reports
    reports: 2
    modmail: "The above {{kind}} by /u/{{author}} has received 2 reports. [Please investigate]({{permalink}})."
 
---
# 3 #Auto approved domains/links -Github
    domain: [github.com]
    action: approve
---
 
# 4 #Mod-Message reports items that could potentially relate to moderators.
    type: any
    title+body: ["moderator", "moderators", "mods", "mod","{{subreddit}}","r/{{subreddit}}"]
    modmail: "The [item]({{permalink}}) mentioned the moderators."
---

###Help Assist
# 5 #Post Logs
    type: comment
    body (full-exact): ["!Logs","!Logging"]
    comment: |
        Hi. OP please review the following link. [Gathering Logs](https://github.com/Sonarr/Sonarr/wiki/Logging-and-Log-Files#sharing-logs) The link is for Sonarr, but the concepts apply for {{subreddit}}.
---

# 6 #Post Download
    type: comment
    body (full-exact): ["!Download","!DownloadImp"]
    comment: |
        Hi. OP please review the following link: [Downloading & Importing](https://github.com/Sonarr/Sonarr/wiki/Downloads-and-Importing) The link is for Sonarr, but the concepts apply for {{subreddit}}.
---

###Post Auto Replies
# 7 #Docker Comment
    type: submission
    Title+body: "docker"
    Comment: |
        You've mentioned Docker, be sure to [generate a docker-compose](https://old.reddit.com/r/usenet/wiki/docker#wiki_get_docker-compose) of all your docker images in a pastebin and link to it. Most Docker issues can be solved by understanding the wiki article for [these automation software and Docker](https://old.reddit.com/r/usenet/wiki/docker), which is all about user, group, ownership, permissions and paths. 
---

# 7.5 #Auto reply if "Downloads, Downloading, Download" is in the body or the title
type: submission
Title+body: ["Downloads", "Downloading", "Download", "import", "imported", "importing", "imports"]
comment: | 
    Hi. OP! It appears that you may be having issues with some aspect of downloading or importing please review the following link. [Downloading & Importing](https://github.com/Sonarr/Sonarr/wiki/Downloads-and-Importing) The link is for Sonarr, but the concepts apply for {{subreddit}}.
---

# 8 #Check if help post has logs
    type: submission
    flair_template_id: e164b166-d373-11ea-ad55-0e35d0a576f3 #arrmodtest unsolved
    #flair_template_id: 5189e338-6761-11e9-bf5a-0ecd7f396b08 #readarr unsolved
    #flair_template_id: 10fa17be-d224-11ea-ae8c-0e9f7c8cd055 #lidarr unsolved
    #flair_template_id: 602b8658-d21d-11ea-b3e4-0ee6a8b990e7 #sonarr unsolved
    #flair_template_id: 245a69ae-d1bf-11ea-bfe5-0ec196655117 #radarr unsolved
    ~body (includes): ["pastebin"]
    Comment: |
        It appears you are requesting assistance and did not provide any linked logs.  Please review the following link. [Gathering Logs](https://github.com/Sonarr/Sonarr/wiki/Logging-and-Log-Files#sharing-logs) The link is for Sonarr, but the concepts apply for {{subreddit}}.
        If you did include the logs directly in your post, please edit your post to remove them and provide the logs via a [pastebin link](pastebin.com) or similar site.
        
        Once your problem is solved, please reply to the answer(s) saying '!solved' in the thread.
    moderators_exempt: false
    comment_locked: true
    comment_stickied: true
---

#8.5 #check to see if logs are not posted to pastebin
  type: submission
  body (includes): ["trace","info","warn"]
  action: filter #filter to mod queue
  action_reason: "Post includes log but not posted to pastebin"
  message_subject: "Post includes log but not posted to pastebin"
  message: |
      Your post has been automatically removed because you have posted logs to reddit. We'd prefer you to upload them to [pastebin link](pastebin.com) or a similar site.
      Please upload your logs and edit your post. Once complete, please send a modmail to let the mods know.
      
      The post is automatically placed in the modqueue and the mods will review it as well for false positives. 
---
  
# 9 #automatic set flair to unsolved if no flair is detected
type: submission
~flair_text (regex): ".+"
set_flair:
  template_id: e164b166-d373-11ea-ad55-0e35d0a576f3 #arrmodtest unsolved
  #template_id: 5189e338-6761-11e9-bf5a-0ecd7f396b08 #readarr unsolved
  #template_id: 10fa17be-d224-11ea-ae8c-0e9f7c8cd055 #lidarr unsolved
  #template_id: 602b8658-d21d-11ea-b3e4-0ee6a8b990e7 #sonarr unsolved
  #template_id: 245a69ae-d1bf-11ea-bfe5-0ec196655117 #radarr unsolved
comment: |
  Hi /u/{{author}} we weren't quite sure what type of post you were looking to make since you did not select a flair type.

  We went ahead and placed your post as an unsolved question. If this is not the case please make changes to correct this.

  If you are requesting assistance and did not provide any linked logs.  Please review the following link. [Gathering Logs](https://github.com/Sonarr/Sonarr/wiki/Logging-and-Log-Files#sharing-logs) The link is for Sonarr, but the concepts apply for {{subreddit}}.

  Once your problem is solved, please reply to the answer(s) saying '!solved' in the thread.  

moderators_exempt: false
comment_locked: true
comment_stickied: true
---

# 10 #Solved Comment for help post
type: comment
body: ["!solved"]
author:
  is_submitter: true
parent_submission:
  flair_template_id: e164b166-d373-11ea-ad55-0e35d0a576f3 #arrmodtest unsolved
  #flair_template_id: 5189e338-6761-11e9-bf5a-0ecd7f396b08 #readarr unsolved
  #flair_template_id: 10fa17be-d224-11ea-ae8c-0e9f7c8cd055 #lidarr unsolved
  #flair_template_id: 602b8658-d21d-11ea-b3e4-0ee6a8b990e7 #sonarr unsolved
  #flair_template_id: 245a69ae-d1bf-11ea-bfe5-0ec196655117 #radarr unsolved
  set_flair:
    template_id: 16d2d504-d378-11ea-a0ae-0e7365d88ae9 #arrmodtest solved
    #template_id: 05ee0a10-d224-11ea-a771-0eab20f8a02f #lidarr solved
    #template_id: 328cdbfe-d211-11ea-aa97-0e384ca82067 #readarr solved
    #template_id: 3ed6a744-d21d-11ea-b58f-0ed8dc567eeb #sonarr solved
    #template_id: 72ec283a-dc3d-11e6-8918-0e7be260da34 #radarr solved
  overwrite_flair: true
comment: "Thank you/u/{{author}} I've gone ahead and marked your post as solved."
moderators_exempt: false
---
### Posts Control
 
# 11 #Moderator Posts
    title (regex): ["mod(erator)?([ -]?post)?s?", "announcements?", "admin(istrator)?s?"]
    action: filter
    action_reason: "Special Mod Words"
    comment: |
        Your post has been automatically removed because you used a keyword which is reserved for the subreddit moderators.
    modmail: |
        The above post by /u/{{author}}, with title "{{title}}" was removed because it contained a moderator-only keyword.
 
        Please investigate and make sure that this action was correct.
---
# Image Direct Links

# 12 #
    domain: [gyazo.com, puu.sh, prntscr.com, postimg.org, pinterest.com, imageshack.us]
    ~url (ends-with): [.png, .jpg, .gif, .jpeg]
    comment: |
        Your submission has been automatically removed due to an indirect link to a hosted image.
 
        Please be considerate of mobile and RES users, and resubmit your link with the proper file extension.
 
        For your convenience, here is your submitted link with a .png file extension appended to the end. Please check that it works. If it does, retry your submission with this link:
 
        {{url}}.png
 
        If the above link does not work, right-click on your image, select *Copy Image URL*, and paste that into the reddit submission page instead.
 
    action: remove
    action_reason: "Indirect Images"
---

# 13 #
    domain: [imgur.com]
    url (regex): ["imgur\\.com/[A-Za-z0-9]{5,8}$"]
    comment: |
        Your submission has been automatically removed due to an indirect link to a hosted image.
 
        Please be considerate of mobile and RES users, and resubmit your post as a direct link.
 
         For your convenience, here is your submitted link with .jpg and .gif file extensions appended to the end. Please see if one works, and re-try your submission with one of the following links:
 
        * {{url}}.jpg
        * {{url}}.gif
 
        If the above links do not work, right-click on your image, select *Copy Image URL*, and paste that into the reddit submission page.
 
    action: remove
    action_reason: "Indirect Images"
---

# 14 #
    domain: [imgur.com]
    url (regex): ["imgur\\.com/[A-Za-z0-9]{5,8},([A-Za-z0-9]{5,8},?)+", "gallery"]
    action: remove
    action_reason: "Indirect Images"
    comment: |
        Your submission has been automatically removed due to an indirect link to a hosted image.
 
        Non-album multi-image links and imgur gallery links are not compatible with RES and mobile apps.
 
        For multi-image links, please create an album and submit a link to that.
 
        For gallery images, please right-click your image, choose *Copy Image URL*, and submit that direct image link to reddit.
---

# 15 #
    domain: [pinterest.com, snag.gy, uput.in, imgflip.com]
    ~url: [i.snag.gy, i.uput.in, i.imgflip.com]
    action: remove
    action_reason: "Indirect Images"
    comment: |
        Your submission has been automatically removed due to an indirect link to a hosted image.
 
        Please right-click your image, choose *Copy Image URL*, and submit that direct image link to reddit.
---

# 16 #
    domain: [tinypic.com]
    action: remove
    action_reason: "Indirect Images"
    comment: |
        Your submission has been automatically removed due to an indirect link to a hosted image.
 
        Unfortunately, the media host {{domain}} is not compatible with mobile apps and/or RES. Please be considerate of mobile and RES users and resubmit your content using a different media host.
---
